### ISSUE TITLE
Never ending disc_projects

### ISSUE THREAD

**Issue by ohphee2lo9Oh** [carlospolop/PurplePanda#25]
Hello,

I tried to run PurplePanda to enumerate GCP as Viewer but disc_projects never ends.

``
$ export GOOGLE_DISCOVERY='Z29vZ2xlOgotIGZpbGVfcGF0aDogIiIK'
$ python3 main.py -e -p google --gcp-get-secret-values
``/opt/PurplePanda/lib/python3.10/site-packages/google/auth/_default.py:83: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive
a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information
about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
[10:12:14] INFO     INFO:core.utils.purplepanda:Enumerating google...                                                                                                                              purplepanda.py:187
/opt/PurplePanda/lib/python3.10/site-packages/google/auth/_default.py:83: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive
a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information
about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
[10:12:21] disc_orgs took 1s                                                                                                                                                                        purplepanda.py:75
[10:12:22] disc_folders took 0s                                                                                                                                                                     purplepanda.py:75
Google disc_projects ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0% • 1 • 0:10:27 ⠏
````````

**Comment by Guerric-H** [comment]
I had the same issue trying to enumerate a project with the Owner role.

**Comment by carlospolop** [comment]
If you try with the latest version is this still happening?

**Comment by carlospolop** [comment]
That can happen if you have tons of permissions being given to the projects. I have added some extra progress bars to help knowing how long will take to check all the ima permissions.
If not enough, feel free to reopen the issue
